---
- hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    - name: update repository index
      apt:
        update_cache: true

    - name: install apache
      apt:
        name: apache2
        state: latest

    - name: installing php support for apache
      apt:
        name: libapache2-mod-php
        state: latest