---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
      remote_user: ubuntu

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
      remote_user: ubuntu

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
      remote_user: ubuntu
