---
- hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    
    - name: update repository index
      package:
        update_cache: yes

    - name: install apache2 and php [ multiple packages ] in a  single module
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution_version == "Ubuntu"




