---

- hosts: all
  become: true
  remote_user:  ubuntu
  tasks:

    

    - name: update repository index
      package:
        update_cache: yes
        

    - name: install apache2 package
    #hostname or groupname , service name , package name 
      tags: ubuntu,apache,apache2
      package:
        name: apache2
        state: latest

    - name: add php support for apache
      tags: ubuntu,php,libapache2-mod-php
      package:
        name: libapache2-mod-php
        state: latest

