

- name: install apache2 package
  #hostname or groupname , service name , package name 
  tags: ubuntu,apache,apache2
  package:
    name:
      - "{{  apache_package_name  }}"
    state: latest




- name: Copy default html files for site on ubuntu
  tags: ubuntu,apache,apache2,httpd
  copy:
    src: default.html
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: 0644
    
- name: add php support for apache
  tags: ubuntu,php,libapache2-mod-php
  package:
    name: 
      - "{{  php_package_name  }}"
    state: latest